#!/usr/bin/env bash

# Check if python3 command exists
if ! command -v python3 >/dev/null 2>&1; then
    echo "Error: python3 is not installed or not in PATH." >&2
    exit 1
fi

count=`ps -ef | grep "python3 WudaoServer.py" | grep -v "grep" | wc -l`
 
if [ $count == 0 ]; then
    nohup python3 WudaoServer.py > ./usr/server.log 2>&1 &
    git pull origin master > ./usr/pull.log 2>&1 &
fi

python3 WudaoCommand.py $*

